#! /bin/sh

# Customs
wal -i /usr/share/wallpapers/ &
picom &
pgrep -x "polybar" > /dev/null || polybar example &
# eval "$(dbus-launch --sh-syntax --exit-with-session)" &
#
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 8 IX X

bspc config border_width         2
bspc config window_gap          10

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
